class ProductModel {
  final String name;
  final String image;
  final double price;
  final String? description;
  final String? productNutritons;
  final String piceis;
  final bool isPopular;
  bool isFavorite;
  final String? category;
  final String? brand;

  ProductModel({
    this.description,
    this.productNutritons,
    required this.name,
    required this.image,
    required this.price,
    required this.piceis,
    this.isPopular = false,
    this.isFavorite = false,
    this.category,
    this.brand,
  });
}

final List<ProductModel> products = [
  ProductModel(
    name: 'Organic Banana',
    image: 'assets/product_details1.png',
    price: 4.99,
    description: 'They are a good source of potassium...',
    productNutritons: '358 mg',
    piceis: '7pcs, Priceg',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Natural Red Apple',
    image: 'assets/product_details2.png',
    price: 4.99,

    description: 'Apple is a sweet and delicious fruit...',
    piceis: '1kg, Priceg',
    productNutritons: '107 mg',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Bell Pepper Red',
    image: 'assets/home_product3.png',
    price: 4.99,

    description: 'Red bell peppers are a vibrant...',
    piceis: '1kg, Priceg',
    productNutritons: 'Vitm:A: 31%',
    isPopular: false,
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Ginger',
    image: 'assets/home_product4.png',
    price: 4.99,

    description: 'Ginger is a rhizome...',
    piceis: '250gm, Priceg',
    productNutritons: '43 mg',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Beef Bone',
    image: 'assets/home_product5.png',
    price: 4.99,

    description: 'Beef bones offer a wealth of nutrients...',
    piceis: '1kg, Priceg',
    productNutritons: '0.5–2 g',
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Chicken Brioller',
    image: 'assets/home_product6.png',
    price: 4.99,

    description: 'Chicken delivers vital nutrients...',
    piceis: '1kg, Priceg',
    productNutritons: '24 mcg',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Kazi Farmas',
  ),
  ProductModel(
    name: 'Diet Cake',
    image: 'assets/bevegares_product1.png',
    price: 1.99,
    piceis: '355ml, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Fast Food',
    brand: 'Cocola',
  ),
  ProductModel(
    name: 'Sprite Can',
    image: 'assets/bevegares_product2.png',
    price: 1.50,
    piceis: '325ml, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Cocola',
  ),
  ProductModel(
    name: 'Apple & Grape',
    image: 'assets/bevegares_product3.png',
    price: 15.99,
    piceis: '2L, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Fast Food',
    brand: 'Ifad',
  ),
  ProductModel(
    name: 'Orenge Juice',
    image: 'assets/bevegares_product4.png',
    price: 1.99,
    piceis: '2L, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    isPopular: true,
    category: 'Fast Food',
    brand: 'Ifad',
  ),
  ProductModel(
    name: 'Coca Cala Can',
    image: 'assets/bevegares_product5.png',
    price: 4.99,
    piceis: '325ml, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Fast Food',
    brand: 'Cocola',
  ),
  ProductModel(
    name: 'Pepsi Can',
    image: 'assets/bevegares_product6.png',
    price: 4.99,

    piceis: '330ml, Price',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Fast Food',
    brand: 'Cocola',
  ),
  ProductModel(
    name: 'Egg Chicken Red',
    image: 'assets/egg_chickenred.png',
    price: 1.99,
    piceis: '4pcs, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Eggs',
    brand: 'Kazi Farmas',
  ),
  ProductModel(
    name: 'Egg Chicken White',
    image: 'assets/egg_chickenwhite.png',
    price: 1.50,
    piceis: '180g, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Eggs',
    brand: 'Kazi Farmas',
  ),
  ProductModel(
    name: 'Egg Pasta',
    image: 'assets/egg_pasta.png',
    price: 15.99,
    piceis: '30gm, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Noodles & Pasta',
    brand: 'Ifad',
  ),
  ProductModel(
    name: 'Egg Noodles',
    image: 'assets/egg_noodles.png',
    price: 15.99,
    piceis: '2L, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Noodles & Pasta',
    brand: 'Ifad',
  ),
  ProductModel(
    name: 'Mayonnais',
    image: 'assets/mayonnais_eggless.png',
    price: 15.99,
    piceis: '1kg, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Fast Food',
    brand: 'Individual Collection',
  ),
  ProductModel(
    name: 'Egg Noodles',
    image: 'assets/egg_nodels.png',
    price: 15.99,
    piceis: '2L, Priceg',
    productNutritons: 'Apple',
    description: 'Apple is a sweet and delicious fruit...',
    category: 'Noodles & Pasta',
    brand: 'Ifad',
  ),
];
